Support  functionality.
ignitionrobotics/ign-msgs pull request #137
Opened 2021-02-25 05:37 UTC by nkoenig

Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🦟 Bug fix

## Summary

The particle emitter message used plain data types. This prevents an Ignition system from knowing if a value has been set. Since we are using the emitter message as the `Component` in Ignition, we need this information.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [X] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [X] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-02-25 18:16 UTC, chapulina requested changes
This breaks API and can't go into a stable release. It needs to be retargeted to `main`, and even then, I think we should consider a tick-tock strategy.

2021-02-25 19:17 UTC, nkoenig commented
> This breaks API and can't go into a stable release. It needs to be retargeted to `main`, and even then, I think we should consider a tick-tock strategy.

The particle emitter was added in the last minor release. I'm making this change in a subsequent minor release. The impact is minimal and is needed by subt.

2021-02-25 20:28 UTC, chapulina commented
Ok, let's make this exception since there are probably no users of particles yet and the release is still fresh. In the future, we should consider making pre-releases for new features that are still under development.

We need to time well the next `ign-msgs6`and `ign-gazebo4` releases so that no users are left in a broken state, and it's very important to set minimum required versions on both `ign-gazebo` and `ign-gazebo4-release`.

Can you add a note about the ABI break to the migration guide?

2021-02-26 12:58 UTC, nkoenig commented
> Can you add a note about the ABI break to the migration guide?

Added in ef3e3f4

2021-02-26 18:26 UTC, chapulina approved these changes

2021-02-26 18:58 UTC, merged